config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    root to: 'devise/sessions#new'
  end

resources :users, only: [:index, :show] do
  resources :posts, only: [:index, :show, :new, :create] do
    resources :comments, only: [ :new, :create]
    resources :likes, only: [:create]
  end
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_save :update_comments_counter

  private

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_posts_like_counter

  private

  def update_posts_like_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes
  after_save :update_posts_counter

  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :title, presence: true, length: { maximum: 250 }

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end

  def most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :confirmable, :validatable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'users_id'
  has_many :likes, foreign_key: 'author_id'
  attribute :posts_counter, :integer, default: 0
  validates :name, presence: true, length: { maximum: 50 }
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?
  def after_sign_in_path_for(_resource)
    users_path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:email, :name, :photo, :bio, :password)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:email, :name, :photo, :bio, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = Comment.new(user_id: @user.id, post: @post, text: params[:comment][:text])
    @comment.save
    redirect_to user_post_path(@user, @post)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = params[:post_id]
    @user = current_user
    @like = Like.new(user_id: @user.id, post_id: @post)

    if @like.save
      flash[:success] = 'Liked successfully.'
    else
      flash.now[:error] = 'Sorry something went wrong'
    end
    redirect_to user_post_path(@user.id, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.where(author_id: params[:user_id])
    @user = User.find(params[:user_id])
  end

  def show
    @post = Post.includes(:author).find(params[:id])
    @comments = @post.comments
    @like = Like.new
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @user = current_user
    @post = Post.new(author_id: @user, title: params[:post][:title], text: params[:post][:text])
    @post.author_id = @user.id
    @post.save
    redirect_to user_posts_path(@user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<section class='new-comment-container'>
  <h2>Add a comment</h2>
  <%= form_with model: @comment, url: user_post_comments_path(@post) do |form| %>
    <div class='comment-form-container'>
      <%= form.text_field :text, required: true, autofocus: true, placeholder: 'Leave a comment', class: "form-input" %>
      <%= form.submit "Comment", class: "form-button" %>
    </div>
    
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
         <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<section class="posts-page">
    <div class="user-container">
        <img src=<%=@user.photo %> alt="user photo">
        <div class="name-and-counter">
            <h1>
                <%= @user.name %>
            </h1>
            <h3 id="post-counter">Number of posts: <%= @user.posts_counter %>
            </h3>
        </div>
    </div>
    <hr>

    <div class="recent-posts">
        <% @posts.includes(comments:[:user]).each do |post| %>
            <%= link_to  user_post_path(@user, post.id) do %>
                <h2><%= post.title %>
                </h2>
                <p id="post-text">
                    <%= post.text.split[0..80].join(" ") %>
                </p>
                <div class="comment-like">
                    <span>Comments: <%= post.comments_counter%>, </span>
                    <span class="likes">Likes:<%= post.likes_counter%></span>
                </div>
                 <% end %>
   
            <% if post.comments_counter != 0 %>
            <hr id="half">
            <% end %>
            <div class="comments-container">
                    <% post.most_recent_comments.each do |comment| %>
                        <div  id="single-comment"> 
                            <span> <%= comment.user.name %> : <%= comment.text %></span>
                        </div>
                    <% end %>
            </div>
             
            <% if post.comments_counter != 0 %>
            <hr id="half">
            <% end %>
        <% end %>
    </div>

    <button>Pagination</button>
</section>

app/views/posts/new.html.erb
<section class="new-post-container">
    <h1>Add New Post</h1>
    <%= form_with model: @post, url: user_posts_path(@user) do |form| %>
      <div class="form-container">
        <%= form.text_field :title, required: true, autofocus: true, class: "form-input" %>
        <%= form.text_area :text, required: true, autofocus: true, class: "form-input" %>
        <%= form.submit "Submit", class: "form-button" %>
      </div>
      
    <% end %>
  </section>

app/views/posts/show.html.erb
<section class="post-page">
    <div class='title-and-info'>
        <h1 id="post-title">
            <%= @post.title%> by <%= @post.author.name%>
        </h1>
        <div class="comment-like-for-post">
            <span>Comments: <%= @post.comments_counter%>, </span>
            <span class="likes">Likes: <%= @post.likes_counter%></span>
        </div>
    </div>
    <p>
        <%= @post.text %>
    </p>
<div class="like-comment-buttons">
  <%= form_with model: @like, url: user_post_likes_path(1, @post), scope: :like do |form|%>
     <%= form.submit 'Like post', class: 'like-button' %>
  <% end %>
  <button type="button" class="comment-button"><%= link_to "Comment", new_user_post_comment_path( post_id: @post.id), { class: "user-link" } %></button>
</div>

    <hr id="post-page-hr">

    <div class="comments-container-post">
        <% @comments=Post.find(@post.id).comments %>
            <% @comments.includes(:user).each do |comment| %>
                <div id="single-comment">
                    <span>
                        <%= comment.user.name %> : <%= comment.text %>
                    </span>
                </div>
                <% end %>
    </div>

    <% if @post.comments_counter !=0 %>
        <hr id="half">
        <% end %>

</section>

app/views/users/index.html.erb
    <div class="users">
        <% @users.each do |user| %>
            <div class="user-container">
                <img src=<%= user.photo %> alt="user photo">
                
                    <div class="name-and-counter">
                        <a href="/users/<%= user.id %>" class="name-and-counter">
                        <h1><%= user.name %></h1>
                        <h3 id="post-counter">Number of posts: <%= user.posts_counter %></h3>
                </a>
                    </div>
            </div>
        <% end %>
    </div>

app/views/users/show.html.erb
<section class="userpage">
    <div class="user-container">
        <img src=<%=@user.photo %> alt="user photo">
        <div class="name-and-counter">
            <h1>
                <%= @user.name %>
            </h1>
            <h3 id="post-counter">Number of posts: <%= @user.posts_counter %>
            </h3>
        </div>
    </div>
    <hr>
    <div class="bio">
        <h2>Bio</h2>
        <p>
            <%= @user.bio %>
        </p>
    </div>
    <hr>
    <div class="recent-posts">
        <% @user.most_recent_posts.each do |post| %>
            <a href="<%=@user.id%>/posts/<%=post.id%>">
                <h2><%= post.title %>
                </h2>
                <p id="post-text">
                    <%= post.text.split[0..80].join(" ") %>
                </p>
                <div class="comment-like">
                    <span class="comments">Comments: <%= post.comments_counter%>, </span>
                    <span class="likes">Likes:<%= post.likes_counter%></span>
                </div>
            </a>
            <% end %>
            <a href="<%=@user.id%>/posts/" class="button">See all posts</a>
    </div>
</section>